<?php

use Illuminate\Database\Seeder;

class EstabelecimentosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('estabelecimentos')->insert([
          'nome'=>'Iate Hotel Florianópolis',
          'email'=>'IateHotel@gmail.com',
          'cnpj'=>'1234567891013',
          'endereco'=>'Rua Silva Jardim, 830 ',
          'cep'=>'88020200',
          'cidade'=>'Florianopolis',
          'estado'=>'Santa Cataria',
          'tel1'=>'8005009959',
          'tel2'=>'4823453456',
          'celular'=>'551199999999',
          'descricao'=>'O Hotel está localizado em área privilegiada de Florianópolis, Santa Catarina, no bairro Prainha, e tem como vista o mar, o iate clube da cidade e o cartão postal da capital catarinense: a ponte Hercílio Luz. Dali, o acesso é fácil tanto para o sul quanto para o norte de Floripa ou mesmo para a saída da Ilha. Ambientes contemporâneos e serviços com a tradição e excelência Plaza Hotéis. O prédio espelhado de construção totalmente nova do Plaza Florianópolis tem design e decoração assinados pelo arquiteto Fernando Loch, profissional de destaque em Santa Catarina. Aqui, você descansará em ambientes modernos e cleans aliados aos serviços de qualidade da Rede Plaza de Hotéis, Resorts & SPAs. O Hotel está pronto para receber você, que vem a negócios ou a lazer a Florianópolis, com muito conforto e uma vista de tirar o fôlego!',
          'wifi'=>'1',
          'cafeDaManha'=>'1',
          'piscina'=>'1',
          'sauna'=>'1',
          'permitePets'=>'1',
          'cancelamentoGratuito'=>'1',
          'numEstrelas'=>'4',
      ]);
      DB::table('estabelecimentos')->insert([
        'nome'=>'Hotel Porto Sol Ingleses',
        'email'=>'portohot@gmail.com',
        'cnpj'=>'1234567891013',
        'endereco'=>'Rua Caminho do Marisco, 80',
        'cep'=>'88058090',
        'cidade'=>'Florianopolis',
        'estado'=>'Santa Catarina',
        'tel1'=>'554832345676',
        'tel2'=>'55243243243',
        'celular'=>'551199999999',
        'descricao'=>'O hotel conta com 60 suítes, que trazem o requinte e o bom gosto necessários para recepcionar bem todos os visitantes. O Hotel coloca à disposição ainda, Restaurante com vista panorâmica para a Praia, lobby bar, serviço de praia, sala de jogos, quadra poliesportiva, volei de praia, piscina, business center e Centro de eventos.',
        'wifi'=>'1',
        'cafeDaManha'=>'1',
        'piscina'=>'1',
        'sauna'=>'1',
        'permitePets'=>null,
        'cancelamentoGratuito'=>null,
        'numEstrelas'=>'3',
      ]);



      DB::table('estabelecimentos')->insert([
        'nome'=>'Club Med Lake Paradise',
        'email'=>'gold@gmail.com',
        'cnpj'=>'1234567891013',
        'endereco'=>'Rodovia Engenheiro Cândido do Rego Chaves, 4500',
        'cep'=>'08751001',
        'cidade'=>'Mogi da Cruzes',
        'estado'=>'São Paulo',
        'tel1'=>'5511123123123',
        'tel2'=>'55243243243',
        'celular'=>'551199999999',
        'descricao'=>'O Club Med Lake Paradise está localizado em Mogi das Cruzes, São Paulo. NAS PROXIMIDADES: O resort fica a 11 Km de distância do Parque Leon Feffer, a 13,8 Km do Parque da Cidade e a 20 Km do Parque Centenário da Imigração Japonesa. O Aeroporto de Guarulhos é o mais próximo, a 45 Km da propriedade. IDEAL PARA: Às margens do lago da Represa Taiaçupeba, o Club Med Lake Paradise é um oásis de paz proporcionando a famílias uma experiência completa de diversão. COMODIDADES: No Lake Paradise, além do tênis, arborismo, mountain bike e golfe, os hóspedes podem experimentar os esportes náuticos no lago, como a vela e o stand up paddle. Podem ainda se refrescar em uma das piscinas ou relaxar nas saunas (seca e a vapor). Para as crianças, há o Mini Club Med e o Junior Club Med, além das atividades para pais e filhos. O resort dispõe também de academia, tratamentos de beleza e bem-estar no Spa e internet Wi-Fi gratuita. O clube conta com dois restaurantes, o Lakeshore e o Loch. O primeiro com uma enorme variedade no buffet, como massas, carnes, frutos do mar, comida japonesa e pizzas.',
        'wifi'=>'1',
        'cafeDaManha'=>'1',
        'piscina'=>'1',
        'sauna'=>'1',
        'permitePets'=>'1',
        'cancelamentoGratuito'=>'1',
        'numEstrelas'=>'5',
      ]);

      DB::table('estabelecimentos')->insert([
        'nome'=>'Yoo2 Rio de Janeiro',
        'email'=>'yoo2@gmail.com',
        'cnpj'=>'1234567891013',
        'endereco'=>'Praia do Botafogo, 242',
        'cep'=>'22250145',
        'cidade'=>'Rio de Janeiro',
        'estado'=>'Rio de Janeiro',
        'tel1'=>'55214231231',
        'tel2'=>'55213243243',
        'celular'=>'552199999999',
        'descricao'=>'Yoo2 Rio de Janeiro conecta alma local com design inovador. Com uma mistura eclética de música que funciona a todo vapor, no Yoo2  Rio de Janeiro você pode desfrutar de um jantar assinado por renomados experts em Gastronomia ou relaxar em volta da piscina do Rooftop com amigos. Os nossos quartos e suites, com as suas vistas espetaculares do Pão de Açúcar e Cristo Redentor, são o espaço perfeito para rejuvenescer a alma e libertar toda sua personalidade.....',
        'wifi'=>'1',
        'cafeDaManha'=>'1',
        'piscina'=>'1',
        'sauna'=>'1',
        'permitePets'=>'1',
        'cancelamentoGratuito'=>'1',
        'numEstrelas'=>'4',
      ]);

      DB::table('estabelecimentos')->insert([
        'nome'=>'Solar do Rosário',
        'email'=>'solardorosario@gmail.com',
        'cnpj'=>'1234567891013',
        'endereco'=>'R. Getulio Vargas, 270',
        'cep'=>'35400000',
        'cidade'=>'Ouro Preto',
        'estado'=>'Minas Gerais',
        'tel1'=>'55135231231',
        'tel2'=>'55133243243',
        'celular'=>'551199999999',
        'descricao'=>'O Hotel Solar do Rosário é um casarão situado no Centro Histórico de Ouro Preto/MG, datado do século XIX, que traz lembranças e belezas originais de uma construção sólida e de uma época áurea, com a herança da boa hospitalidade mineira. Impressiona pelo conjunto de portas que compõem a sua fachada, o balcão inglês que circunda o solar e a sua localização privilegiada junto à Igreja do Rosário, com vista das Igrejas de São Francisco de Paulo, Nossa Senhora do Rosário, São José e o Pico do Itacolomi. O edifício foi totalmente reformado e reestruturado para alocar, com muito conforto, os seus hóspedes.',
        'wifi'=>'1',
        'cafeDaManha'=>'1',
        'piscina'=>'1',
        'sauna'=>'1',
        'permitePets'=>'0',
        'cancelamentoGratuito'=>'0',
        'numEstrelas'=>'3',
      ]);
      DB::table('estabelecimentos')->insert([
        'nome'=>'Pousada Céu da Mantiqueira',
        'email'=>'ceudamantiqueira@gmail.com',
        'cnpj'=>'1234567891013',
        'endereco'=>'Estrada da Embratel',
        'cep'=>'37640000',
        'cidade'=>'Extrema',
        'estado'=>'Minas Gerais',
        'tel1'=>'5513123123123',
        'tel2'=>'551332432436',
        'celular'=>'551199999999',
        'descricao'=>'A Pousada Céu da Mantiqueira é um paraíso escondido no alto da Serra da Mantiqueira, na cidade de Extrema- MG. Com um visual panorâmico único, a pousada oferece tranquilidade, privacidade e conforto em meio a uma natureza exuberante.Nossa infraestrutura conta com piscina, nascentes, pequenos lagos, bosque com redes, estacionamento, sala de jogos, sala de tv com DVD e lareira, internet, tv via satélite e restaurante com comida típica mineira. Um lugar para relaxar, descansar, refazer o seu equilíbrio e estar conectado com a natureza a apenas 100 km de São Paulo e Campinas.',
        'wifi'=>'1',
        'cafeDaManha'=>'1',
        'piscina'=>'1',
        'sauna'=>'1',
        'permitePets'=>'0',
        'cancelamentoGratuito'=>'0',
        'numEstrelas'=>'3',
      ]);

      DB::table('estabelecimentos')->insert([
          'nome'=>'Pantanal Mato Grosso Hotel',
          'email'=>'pantanalHotel@gmail.com',
          'cnpj'=>'1874567891013',
          'endereco'=>'Estrada Transpantaneira, 65',
          'cep'=>'78175000',
          'cidade'=>'Poconé',
          'estado'=>'Mato Grosso ',
          'tel1'=>'5547123123123',
          'tel2'=>'554832432434',
          'celular'=>'551199999999',
          'descricao'=>'O Pantanal Mato Grosso Hotel está situado em Poconé, Mato Grosso. NAS PROXIMIDADES: Localizado no pantanal mato-grossense, o Pantanal Mato Grosso Hotel fica a 2 horas e 40 minutos do Aeroporto Internacional de Cuiabá. IDEAL PARA: Ideal para quem deseja dar um tempo do barulho da cidade grande e apreciar a natureza. COMODIDADES: A propriedade oferece sala de jogos, sala de TV, bar, restaurante, piscina, bar de piscina, estacionamento gratuito, parquinho, esportes aquáticos, serviço de limpeza diário e loja de lembranças. PETS: Animais de estimação não são permitidos. ACOMODAÇÃO: As acomodações do Pantanal Mato Grosso Hotel são bem arejadas e contam com banheiro privativo e ar-condicionado. COMO CHEGAR: Avião+ transfer; carro; ônibus saindo principalmente de Cuiabá.',
          'wifi'=>'1',
          'cafeDaManha'=>'1',
          'piscina'=>'1',
          'sauna'=>'1',
          'permitePets'=>'1',
          'cancelamentoGratuito'=>'0',
          'numEstrelas'=>'3',
      ]);
      DB::table('estabelecimentos')->insert([
          'nome'=>'Hotel Mato Grosso Águas Quentes',
          'email'=>'rioquante@gmail.com',
          'cnpj'=>'1234567891013',
          'endereco'=>'Rodovia. BR 364 - KM77, s/n',
          'cep'=>'78181970',
          'cidade'=>'Santo Antonio Do Leverger',
          'estado'=>'Mato Grosso',
          'tel1'=>'5511123123123',
          'tel2'=>'55243243243',
          'celular'=>'551199999999',
          'descricao'=>'O Hotel Mato Grosso Águas Quentes está situado em Santo Antônio do Leverger, Mato Grosso. NAS PROXIMIDADES: Localizado à 85 km da área urbana de Cuiabá, na Serra de São Vicente, o Hotel Mato Grosso Águas Quentes faz parte do Parque Estadual de Águas Quentes, área de preservação e possui a chancela do selo ISO 14001 que presa pela preservação do meio ambiente e pelas práticas sustentáveis entre o turismo e a natureza. IDEAL PARA: Considerado um dos melhores Hotéis de águas termais do Brasil, o Hotel Mato Grosso Águas Quentes é ideal para curtir em casal, família ou amigos. COMODIDADES: O Hotel Mato Grosso Águas Quentes oferece piscina, tobogã, brinquedos aquáticos infantis, piscina coberta, cachoeiras e piscinas de águas termais com temperatura entre 37 e 42 graus Celsius. Também possui atividades como tirolesa, arborismo e a pista de caminhada. A estrutura do hotel também prevê atividades para executivos, inclusive com centro de convenções para 300 pessoas.',
          'wifi'=>'1',
          'cafeDaManha'=>'1',
          'piscina'=>'1',
          'sauna'=>'1',
          'permitePets'=>'1',
          'cancelamentoGratuito'=>'0',
          'numEstrelas'=>'3',
      ]);
      DB::table('estabelecimentos')->insert([
          'nome'=>'Pousada Mar Aberto',
          'email'=>'maraberto@gmail.com',
          'cnpj'=>'1234567891013',
          'endereco'=>'Alameda das Flores, 02',
          'cep'=>'1234567',
          'cidade'=>'Fernando De Noronha',
          'estado'=>'Pernambuco',
          'tel1'=>'5578123123123',
          'tel2'=>'55673243243',
          'celular'=>'557699999999',
          'descricao'=>'A Pousada Mar Aberto está localizada na Vila da Floresta Nova, com ótima localização e próxima da Vila dos Remédios, Praia do Cachorro e também de vários restaurantes, farmácia, banco, hospital e lojas. Dispomos de Wi-Fi gratuito em toda a propriedade, piscina ao ar livre e um interior aconchegante e convidativo, com detalhes rústicos e decoração regional. Nosso buffet de café da manhã inclui frutas, sucos, uma variedade de pães, bolos e itens de confeitaria de produção própria, além de comidinhas regionais. Também servimos um delicioso chá da tarde nas segundas, quartas e sextas. Tudo incluso no seu pacote. Todos os nossos apartamentos são para não fumantes, com camas box, banheiro privativo com chuveiro aquecido por energia solar, secador de cabelo, ar condicionado com sistema Inverter, TV a cabo, frigobar, telefone, guarda-chuvas e cofre. O Aeroporto de Fernando de Noronha encontra-se a 5 km da pousada',
          'wifi'=>'1',
          'cafeDaManha'=>'1',
          'piscina'=>'1',
          'sauna'=>'1',
          'permitePets'=>'0',
          'cancelamentoGratuito'=>'0',
          'numEstrelas'=>'4',
      ]);
            DB::table('estabelecimentos')->insert([
              'nome'=>'Pousada Estrela do Mar ',
              'email'=>'estreladomar@gmail.com',
              'cnpj'=>'1234567891013',
              'endereco'=>'Loc Conj Res Floresta Nova 571',
              'cep'=>'1234567',
              'cidade'=>'Fernando De Noronha',
              'estado'=>'Pernambuco',
              'tel1'=>'5578123123123',
              'tel2'=>'557832432433',
              'celular'=>'551199999999',
              'descricao'=>'A Pousada Estrela do Mar está localizada em Fernando de Noronha, Pernambuco. NAS PROXIMIDADES: Situada em uma propriedade cercada por jardins e árvores, a Pousada Estrela do Mar está a 5 minutos de carro do Projeto Tamar, a 12 minutos de carro do Mirante dos Golfinhos, a cerca de 1km de distância da Praia do Cachorro, a 11 minutos de carro da Praia do Sancho e a 8 minutos também de carro da Baía dos Porcos, além de ficar a 4 minutos de caminhada do Restaurante Xica da Silva, a 7 minutos de carro do Bar do Meio Noronha e a apenas 7 minutos de carro do Aeroporto de Fernando de Noronha. IDEAL PARA: Esta pousada de estilo rústico em um cenário paradisíaco garante aos viajantes uma estadia com o máximo de conforto, tranquilidade e uma ótima localização, sendo ideal para viagens em família e também para casais, já que a estética do local favorece o clima romântico. COMODIDADES: A Pousada Estrela do Mar oferece estacionamento gratuito, WIFI, acessibilidade para hóspedes cadeirantes, serviço de lavanderia, atividades recreativas, além de serviços de aluguel de bicicletas e bugues (carro). REFEIÇÃO: Café da manhã incluso na diária. PETS: Animais de estimação não são aceitos. ACOMODAÇÕES: As charmosas acomodações da Pousada Estrela do Mar dispõem de varandas com rede, banheiro privativo, ar-condicionado, TV de LED com canais por assinatura, frigobar, cofre e WIFI, além de apresentarem um formato encantador de bangalô. COMO CHEGAR: Avião saindo de Recife ou Natal + transfer.',
              'wifi'=>'1',
              'cafeDaManha'=>'1',
              'piscina'=>'1',
              'sauna'=>'1',
              'permitePets'=>'0',
              'cancelamentoGratuito'=>'0',
              'numEstrelas'=>'4',
                  ]);

            DB::table('estabelecimentos')->insert([
              'nome'=>'Fasano Rio de Janeiro',
              'email'=>'fasanoRJ@gmail.com',
              'cnpj'=>'1234567891013',
              'endereco'=>'Avenida Viera Souto, 80',
              'cep'=>'22420002',
              'cidade'=>'Rio de Janeiro',
              'estado'=>'Rio de Janeiro',
              'tel1'=>'5521123123123',
              'tel2'=>'55213243243',
              'celular'=>'551199999999',
              'descricao'=>'O Fasano Rio de Janeiro está situado em Rio de Janeiro, RJ. NAS PROXIMIDADES: Localizado no badalado bairro de Ipanema, o Fasano Rio de Janeiro está próximo a vários bares e restaurantes descontraídos à beira-mar, além de ficar a menos de 1 hora do Cristo Redentor, a meia hora do Pão de Açúcar, a 15 minutos do Jardim Botânico, a 20 minutos do Terminal Rodoviário Novo Rio e a 35 minutos do Aeroporto Internacional do Galeão. IDEAL PARA: Este luxuoso hotel tem como objetivo oferecer o máximo de sofisticação, bem-estar e comodidade para seus hóspedes, sendo ele ideal para viajantes tanto a trabalho quanto a lazer. COMODIDADES: O Fasano Rio de Janeiro oferece dois restaurantes de conceitos distintos para atender a diferentes momentos gastronômicos do dia e um bar na piscina com vista panorâmica da Praia de Ipanema. A propriedade ainda conta com uma linda piscina de borda infinita com vista para o mar, um SPA localizado no primeiro andar do prédio com uma variedade de terapias relaxantes, tratamentos estéticos e serviços de salão de beleza, um fitness center, business center e serviço de praia. PETS: Animais de estimação são permitidos (mediante solicitação). ACOMODAÇÕES: As acomodações do Fasano Rio de Janeiro são muito amplas e todas possuem banheiro privativo, TV a cabo e workstation. As camas king-size têm lençóis de algodão egípcio com 300 fios, travesseiros e duvet de pluma de ganso, e foram estrategicamente posicionadas para o horizonte, maximizando a vista para a orla e o mar. COMO CHEGAR: Avião+ transfer; carro; ônibus saindo de São Paulo, Belo Horizonte, Vitória, entre outros.',
              'wifi'=>'1',
              'cafeDaManha'=>'1',
              'piscina'=>'1',
              'sauna'=>'1',
              'permitePets'=>'1',
              'cancelamentoGratuito'=>'0',
              'numEstrelas'=>'5',
            ]);





            DB::table('estabelecimentos')->insert([
              'nome'=>'Sheraton Santos',
              'email'=>'Sheraton.santos@gmail.com',
              'cnpj'=>'1234567891013',
              'endereco'=>'R. Guaiaó, 70',
              'cep'=>'11035260',
              'cidade'=>'Santos',
              'estado'=>'São Paulo',
              'tel1'=>'5513123123123',
              'tel2'=>'55133243243',
              'celular'=>'551399999999',
              'descricao'=>'*****PROMOÇÃO ESPECIAL DE PAGUE 3 NOITES, FIQUE 4; 2 CRIANÇAS GRÁTIS ATÉ 12 ANOS; Sujeito a Disponibilidade no Período; Early Check in mediante disponibilidade; 10% OFF em A&B Exceto Alcoólicos***** O Sheraton Santos está situado em Santos, São Paulo. NAS PROXIMIDADES: Possuindo uma ótima localização próximo ao Porto de Santos, o Hotel Sheraton fica a 5km da balsa que liga Santos- Guarujá, a 15 minutos de distância do Mendes Convention Center, a 9 minutos do Aquário Municipal, a 50 minutos da Praia do Guaiuba e a menos 2 horas Aeroporto Internacional de Guarulhos. IDEAL PARA: Ideal para viajantes que desejam ter a facilidade de ter tudo perto de sua estadia. COMODIDADES: A propriedade oferece piscina interior com bar, restaurante, recepção 24 horas, sala de jogos, mesa de bilhar, sala de reuniões, academia, kids club, SPA, business center, estacionamento e serviço de limpeza diário. PETS: Animais de estimação de até 18kg são permitidos em algumas acomodações (mediante a pedido). ACOMODAÇÕES: As acomodações do Sheraton Santos são muito confortáveis e contam com banheiro privativo, ar-condicionado, televisão, cofre e minibar. COMO CHEGAR: Avião+ transfer; carro; ônibus saindo de Curitiba, São Paulo, Belo Horizonte, entre outros.',
              'wifi'=>'1',
              'cafeDaManha'=>'1',
              'piscina'=>'1',
              'sauna'=>'1',
              'permitePets'=>'1',
              'cancelamentoGratuito'=>'0',
              'numEstrelas'=>'4',
            ]);

            DB::table('estabelecimentos')->insert([
              'nome'=>'Novotel Santos',
              'email'=>'novotel@gmail.com',
              'cnpj'=>'1234567891013',
              'endereco'=>'Av. Dona Ana Costa, 473 - Gonzaga',
              'cep'=>'11060003',
              'cidade'=>'Santos',
              'estado'=>'São Paulo',
              'tel1'=>'5513123123123',
              'tel2'=>'55133243243',
              'celular'=>'551399999999',
              'descricao'=>'O Novotel Santos está situado em Santos, São Paulo. NAS PROXIMIDADES: Localizado no coração da cidade, o Novotel Santos possui acesso ao Shopping Pátio Iporanga e ao Shopping Miramar, além de estar a 500 metros da Praia do Gonzaga, a 700 metros do Centro de Convenções Mendes e a 1 hora e 40 minutos do Aeroporto Internacional de Guarulhos. IDEAL PARA: Este hotel 4 estrelas é ideal para viajantes que desejam uma estadia com mais conforto e que esteja perto de praias, lojas e restaurantes. COMODIDADES: O Novotel Santos oferece estacionamento (pago), lavanderia, recepção 24 horas, acessibilidade para cadeira de rodas, academia, sauna, bar, restaurante, serviço de quarto, 3 salas de reuniões e serviço de cópia. PETS: Animais de estimação de pequeno porte são permitidos. ACOMODAÇÕES: As acomodações do Novotel Santos são amplas e adaptáveis a suas necessidades, além de contarem com banheiro privativo, WIFI, minibar e telefone. COMO CHEGAR: Avião+ transfer; carro; ônibus saindo principalmente de São Paulo.',
              'wifi'=>'1',
              'cafeDaManha'=>'1',
              'piscina'=>'1',
              'sauna'=>'1',
              'permitePets'=>'1',
              'cancelamentoGratuito'=>'1',
              'numEstrelas'=>'4',
            ]);

            DB::table('estabelecimentos')->insert([
              'nome'=>'Pousada Recanto da Coruja',
              'email'=>'Rcoruja@gmail.com',
              'cnpj'=>'1234567891013',
              'endereco'=>'Quadra D Lote 13',
              'cep'=>'55590000',
              'cidade'=>'Porto de Galinhas',
              'estado'=>'Pernambuco',
              'tel1'=>'5521123123123',
              'tel2'=>'55213243243',
              'celular'=>'551199999999',
              'descricao'=>'A Pousada Recanto da Coruja é um local com muito charme, aconchego, beleza natural e muito verde. Tudo foi carinhosamente decorado para oferecer o máximo de conforto e tranquilidade. A Pousada fica a 200 metros da praia do Cupe e a 5 minutos (de carro) do centrinho (4,0 km) de Porto. Relaxe em nossa área de lazer tomando um refrescante banho na piscina com cachoeira, som ambiente e choupanas com serviços de bar e um cardápio variado com deliciosos drinks e petiscos. Possui internet wireless e câmeras de segurança em toda pousada, bem como restaurante climatizado e decorado. As caiçaras com redes para relax e leitura são um convite à preguiça. Na Pousada Recanto da Coruja, você é nosso convidado a desfrutar o que Porto de Galinhas tem de melhor.',
              'wifi'=>'1',
              'cafeDaManha'=>'1',
              'piscina'=>'1',
              'sauna'=>'1',
              'permitePets'=>'1',
              'cancelamentoGratuito'=>'0',
              'numEstrelas'=>'3',
            ]);

            DB::table('estabelecimentos')->insert([
              'nome'=>'Blue Tree Towers Anália Franco',
              'email'=>'BtreeAF@gmail.com',
              'cnpj'=>'1234567891013',
              'endereco'=>'RUA ELEONORA CINTRA, 960 TATUAPÉ',
              'cep'=>'03337000',
              'cidade'=>'São Paulo',
              'estado'=>'São Paulo',
              'tel1'=>'5511123123123',
              'tel2'=>'55113243243',
              'celular'=>'551199999999',
              'descricao'=>'Situado em um dos bairros mais nobres de São Paulo o Blue Tree Towers Anália Franco esta localizado em frente ao belíssimo Parque Ceret que possui uma vista de tirar o fôlego com seus 286.000m² e conta com pistas de caminhada e corridas, além de mais de 20 quadras esportivas campos de futebol e balneário de piscinas, ao lado do conceituado Shopping Anália Franco (200 m), melhor opção de compras da região. Localizado há 3,5km da estação de metrô Carrão e em um raio de 1,5km poderá encontrar mais de 30 opções de gastronomia entre bares e restaurantes. Com acomodações modernas todos os quartos do hotel dispõem de ar-condicionado split (quente e frio), TV a cabo, excelente wifi gratuito, frigobar e cofre digital. Somos o único hotel da região que oferece uma glamurosa Suíte Master com 37m² e mini cozinha. Oferecemos quatro diferentes acomodações e algumas com uma maravilhosa vista panorâmica do parque CERET e sacada. O hotel possui restaurante com menu internacional, especializado nas culinárias italiana e brasileira, o Gastronomia Albuquerque conta com espaço aconchegante e charmoso para atender nossos hóspedes. Além disso, a propriedade dispõe de um lindo espaço com piscina ao ar livre onde os hóspedes podem relaxar e uma confortável sala de TV. Para sua melhor comodidade o hotel dispõe de estacionamento privativo com serviço de manobrista, mediante taxa diária. Estamos localizados há 9 km do Expo Center Norte, 13 km do Pavilhão Anhembi centro de convenções onde acontecem grandes eventos em São Paulo e 13 km da Arena Corinthians (Arena sede da Copa do Mundo 2014 e Olimpíadas 2016). Somos o hotel de São Paulo mais próximo do Aeroporto Internacional de Guarulhos, 23 km com rápido e fácil acesso.',
              'wifi'=>'1',
              'cafeDaManha'=>'1',
              'piscina'=>'1',
              'sauna'=>'1',
              'permitePets'=>'1',
              'cancelamentoGratuito'=>'0',
              'numEstrelas'=>'4',
            ]);

            DB::table('estabelecimentos')->insert([
              'nome'=>'Casa Mar Paraty',
              'email'=>'casaMar@gmail.com',
              'cnpj'=>'1234567891013',
              'endereco'=>'Rodovia BR-101 nº 565 Parati',
              'cep'=>'23970000',
              'cidade'=>'Parati',
              'estado'=>'Rio de Janeiro',
              'tel1'=>'5521123123123',
              'tel2'=>'55213243243',
              'celular'=>'551199999999',
              'descricao'=>'Situada em uma vila de pescadores e a poucos metros da Prainha, a Casa Mar Paraty dispõe de uma piscina ao ar livre e Wi-Fi gratuito. Todos os quartos possuem ar-condicionado, varanda, cofre, roupa de cama e banheiro privativo com produtos de banho de cortesia. As acomodações também oferecem vista do mar. A Casa Mar Paraty dispõe de um bar. A propriedade também oferece outras comodidades, incluindo esportes aquáticos e depósito para bagagem. Você ainda pode desfrutar de diversas atividades no local ou nos arredores, incluindo trilhas a pé, mergulho com snorkel e canoagem. Além disso, um estacionamento gratuito está disponível na propriedade.',
              'wifi'=>'1',
              'cafeDaManha'=>'1',
              'piscina'=>'1',
              'sauna'=>'1',
              'permitePets'=>'1',
              'cancelamentoGratuito'=>'0',
              'numEstrelas'=>'4',
            ]);

            DB::table('estabelecimentos')->insert([
              'nome'=>'Pousada Estrela Alpina',
              'email'=>'Estrela-Alpina@gmail.com',
              'cnpj'=>'1234567891013',
              'endereco'=>'Rua do Bosque Monte Verde)',
              'cep'=>'37653000',
              'cidade'=>'Camanducaia',
              'estado'=>'Minas Gerais',
              'tel1'=>'5515123123123',
              'tel2'=>'551532432434',
              'celular'=>'551199999999',
              'descricao'=>'A Pousada Estrela Alpina é a melhor opção para quem procura o charme, a segurança e a tranquilidade de um ambiente romântico no friozinho da montanha. Com ambientes agradáveis, A pousada Estrela Alpina possui 20 charmosas suítes. É ideal para descansar, namorar e curtir a natureza. Em Estilo campestre, a 1800 m de altitude e a 3,5 do centrinho, aqui você encontra um atendimento personalizado, estacionamento, jardins com vistas maravilhosas, sala de estar e de refeições com lareira e um delicioso café da manhã que vai ate às 11:00 hs.',
              'wifi'=>'1',
              'cafeDaManha'=>'1',
              'piscina'=>'1',
              'sauna'=>'1',
              'permitePets'=>'1',
              'cancelamentoGratuito'=>'0',
              'numEstrelas'=>'3',
            ]);

            DB::table('estabelecimentos')->insert([
              'nome'=>'Four Points by Sheraton Curitiba',
              'email'=>'FPBSC@gmail.com',
              'cnpj'=>'1234567891013',
              'endereco'=>'Av. Sete de Setembro, 4211',
              'cep'=>'22420002',
              'cidade'=>'Curitiba',
              'estado'=>'Parana',
              'tel1'=>'5543123123123',
              'tel2'=>'55433243243',
              'celular'=>'551199999999',
              'descricao'=>'O Four Points by Sheraton Curitiba está situado em Curitiba, Paraná. NAS PROXIMIDADES: Localizado estrategicamente no centro da cidade, bem próximo a restaurantes e do centro empresarial, o Four Points by Sheraton Curitiba encontra-se a 5 minutos do shopping Curitiba, a 15 minutos do Jardim Botânico e a 25 minutos do Aeroporto Internacional Afonso Pena. IDEAL PARA: Eleito 9 vezes seguidas como o melhor hotel de Curitiba e premiado com o “Traveler’s Choice 2016”, o Four Points by Sheraton Curitiba é o hotel ideal para você que busca conforto e tranquilidade para toda família. COMODIDADES: O Four Points by Sheraton Curitiba oferece estrutura e serviços completos para que você aproveite cada segundo de sua hospedagem: piscina semiolímpica coberta e climatizada, saunas secas e úmidas, fitness center, Spa com várias opções de terapia e relaxamento e muito mais. Se sua viagem for a trabalho, você ainda pode contar com o maior centro de convenções da cidade, que possui 13 salas amplas. PETS: Animais de estimação não são permitidos. ACOMODAÇÕES: As acomodações do Four Points by Sheraton Curitiba são amplas e muito sofisticadas, além de contarem com banheiro privativo, ar-condicionado e TV a cabo. COMO CHEGAR: Avião+ transfer; carro; ônibus saindo de Rio de Janeiro, Joinville, Londrina, entre outros.',
              'wifi'=>'1',
              'cafeDaManha'=>'1',
              'piscina'=>'1',
              'sauna'=>'1',
              'permitePets'=>'1',
              'cancelamentoGratuito'=>'0',
              'numEstrelas'=>'5',
            ]);
    }
}
